# Use the official nginx:stable image as the base image
FROM nginx:stable

# Copy the project files into the Docker image
COPY web/ /usr/share/nginx/html

# Expose port 80 so that the container can be accessed via a web browser
EXPOSE 80
